name: Build & Test @3xpo/fs-extra

on:
  push:
    branches: ['master']
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    strategy:
      matrix:
        node: [16.x, 18.x, 19.x, 20.x, 21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone Repo
        run: |
          git clone https://codeberg.org/Expo/pkgs.git .
      - name: 'MacOS: Install distutils/setuptools'
        if: matrix.os == 'macos-latest'
        run: |
          pip install setuptools
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node }}
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm i --no-frozen-lockfile
      - name: Install dependencies, again
        run: cd packages/@3xpo/fs-extra && pnpm i --no-frozen-lockfile
      - name: Build
        run: pnpm nx build @3xpo/fs-extra
      - name: Test
        run: pnpm nx run @3xpo/fs-extra:test
