name: Node.js CI
on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        node: [14.x, 16.x, 18.x, 20.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build
      - run: npm test
