name: Deploy @3xpo/fs-extra
run-name: Deploy @3xpo/fs-extra
on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/senpai'
    runs-on: docker
    container:
      image: 3xpo/base
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Git
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVK }}" > ~/.ssh/id_ed25519
          echo "${{ secrets.PUBK }}" > ~/.ssh/id_ed25519.pub
          chmod 700 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Clone repository
        run: |
          git clone -b master --single-branch git@github.com:Exponential-Workload/modern-fs-extra.git ../ev-repo
          cd ../ev-repo
          git config user.email "eventpush@no"
          git config user.name "Codeberg Actions"
          git config --local http.extraheader "AUTHORIZATION: basic ${{ secrets.EVENT_PAT }}"
          cd -
      - name: Setup package
        run: |
          cp -r packages/@3xpo/fs-extra ../ev-out
          cp -r ../ev-repo/.git ../ev-out/.git
          git rev-parse HEAD > ../ev-out/.rev
      - name: Update README
        run: |
          cd ../ev-out;
          mv README.md R
          cat README.github.md R > README.md
          rm README.github.md R
      - name: Commit and push changes
        run: |
          cd ../ev-out
          echo .rev >> .gitignore
          git add .
          git commit -m "chore: Update to Codeberg/$(cat .rev)" --allow-empty
          git push --force git@github.com:Exponential-Workload/modern-fs-extra.git master
