name: Deploy pkgs
run-name: Deploy pkgs
on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/senpai'
    runs-on: docker
    container:
      image: archlinux
    steps:
      - name: Install System Deps
        run: pacman -S --noconfirm git openssh base-devel findutils
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Git
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PRIVK }}" > ~/.ssh/id_ed25519
          echo "${{ secrets.PUBK }}" > ~/.ssh/id_ed25519.pub
          chmod 700 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Setup package
        run: |
          git config user.email "eventpush@no"
          git config user.name "Codeberg Actions"
          git config --local http.extraheader "AUTHORIZATION: basic ${{ secrets.EVENT_PAT }}"
          git remote set-url origin git@github.com:Exponential-Workload/pkgs.git
      - name: Commit and push changes
        run: |
          git remote set-url origin git@codoeberg.org:Expo/pkgs.git
          git push --force git@github.com:Exponential-Workload/pkgs.git senpai
      - name: Update READMEs
        run: |
          find . -type f -name 'README.md' -exec 'bash' '-c' 'cat README.github.md "{}" > "{}.new"' \;
          find . -type f -name 'README.md' -exec 'mv' '{}.new' '{}' \;
      - name: Commit and push new READMEs
        run: |
          git add .
          git push --force git@github.com:Exponential-Workload/pkgs.git senpai
          git commit -m "chore: Update READMEs @ $(git rev-parse HEAD)" --allow-empty
          git push --force git@github.com:Exponential-Workload/pkgs.git senpai
