name: Build & Test Packages
run-name: Build & Test Packages
on: [push]

jobs:
  build:
    runs-on: docker
    container:
      image: 3xpo/base
    steps:
      - name: Install System Dependencies
        run: pacman -S --noconfirm --needed g++ cmake
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Install Dependencies
        run: pnpm i --no-frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
