name: Build & Test Packages
run-name: Build & Test Packages
on: [push]

jobs:
  build:
    runs-on: docker
    container:
      image: node
    steps:
      - name: Install System Dependencies
        run: apt update && apt install git g++ cmake -y
      - name: Checkout
        uses: actions/checkout@v3
      - name: Enable Corepack
        run: corepack enable
      - name: Install Dependencies
        run: pnpm i --no-frozen-lockfile
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
