name: Build & Test @3xpo/events

on:
  push:
    branches: ['master']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        run: |
          git clone https://codeberg.org/Expo/devtools.git .
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 20
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies
        run: pnpm i
      - name: Build
        run: cd packages/@3xpo/events && pnpm build
      - name: Test
        run: cd packages/@3xpo/events && pnpm test
      - name: Make Documentation
        run: cd packages/@3xpo/events && pnpm mkdocs
      - name: Copy Docs
        run: cd packages/@3xpo/events && cp -r docs/* ./
      - name: Destroy Node Modules
        run: cd packages/@3xpo/events && rm -rf node_modules
      - name: Create Indexes
        uses: Exponential-Workload/create-index-action@master
        with:
          dir: 'packages/@3xpo/events'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'packages/@3xpo/events'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
