name: gtfo

on:
  pull_request:
    types: [opened]

jobs:
  redirect-and-close:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const message = `
            Hello @${{ github.event.pull_request.user.login }},

            Thank you for your contribution! However, this repository is a read-only mirror. Please re-open this over at https://codeberg.org/Expo/pkgs - this should take no more than a few minutes:
            1. Create an account on Codeberg, if you don't already have one.
            2. Verify it's email.
            3. Add your SSH key to your Codeberg account.
            4. Fork the repository.
            5. Run `git remote set-url origin git@codeberg.org:[your username]/pkgs.git` in your fork's git repository.
            6. Run `git push`, as you normally would.
            7. Open a PR on Codeberg.
            8. Enjoy!

            This PR will be closed automatically.
            `.split('\n').map(v=>v.trim()).join('\n').trim();
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            });

      - name: Close PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              state: "closed"
            });
